### ISSUE TITLE
GroundTurth of Presudo

### ISSUE THREAD

**Issue by pure-sky** [zengzhenhuan/GFNet#1]
Hi zengzhenhuan,
      I have an issue with the Presudo GT. Why are your presudo labels as well as the labels of [Inf-net](https://github.com/DengPingFan/Inf-Net)? Can you release the labels of the GFnet? I look forward to your reply.
Best,
pure-sky

**Comment by zengzhenhuan** [comment]
I'm sorry, I uploaded the wrong data set. Now I have graduated, and the relevant datas of this paper was not been saved. You can download the Inf-Net code, which has a file for generating presudo labels, and replace my model with Inf-Net to generate GFNet's presudo labels data set.

**Comment by pure-sky** [comment]
Hi zengzhenhuan,
Thanks for your reply! I am so sad about the data lost. I will try to repeat the presudo labels generations late. And I found an inconsistent Bug at line 42 in the code of _mytest_VGG_ [line 42](https://github.com/zengzhenhuan/GFNet/my_test_VGG.py). The model only returns seven feature maps that not aggarent your expected. I try to change the final_map to the sum of lateral_map5, lateral_map4, lateral_map3, lateral_map2, lateral_map1. I'm not sure that the fuse block is what your expected. May I get your email site for further exchange.
I am so glad for your reply. You can close the issue.  I look forward to your reply about that Bug.
Best,
pure-sky

**Comment by zengzhenhuan** [comment]
These seven results should be lateral_map(1-5) , lateral_edge(generated by the edge_guidance module) and a highmap(generated by the aggregation module). The final result is obtained by adding the results of each layer，res=lateral_map1+...+lateral_map5. However, please note that there may be some differences between the results running on your computer and mine. This is normal, because of the different machine configuration and experimental environment.

**Comment by pure-sky** [comment]
Hi zengzhenhuan,
Thanks for your quick reply! Your work is very nice!
Best,
pure-sky
